// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// hashDataFrame
DataFrame hashDataFrame(DataFrame df, int numCols, int hashSeed, std::string factorMode);
RcppExport SEXP amsteRdam_hashDataFrame(SEXP dfSEXP, SEXP numColsSEXP, SEXP hashSeedSEXP, SEXP factorModeSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< int >::type numCols(numColsSEXP);
    Rcpp::traits::input_parameter< int >::type hashSeed(hashSeedSEXP);
    Rcpp::traits::input_parameter< std::string >::type factorMode(factorModeSEXP);
    __result = Rcpp::wrap(hashDataFrame(df, numCols, hashSeed, factorMode));
    return __result;
END_RCPP
}
// explainHashDataFrame
List explainHashDataFrame(DataFrame df, int numCols, int hashSeed, std::string factorMode);
RcppExport SEXP amsteRdam_explainHashDataFrame(SEXP dfSEXP, SEXP numColsSEXP, SEXP hashSeedSEXP, SEXP factorModeSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< int >::type numCols(numColsSEXP);
    Rcpp::traits::input_parameter< int >::type hashSeed(hashSeedSEXP);
    Rcpp::traits::input_parameter< std::string >::type factorMode(factorModeSEXP);
    __result = Rcpp::wrap(explainHashDataFrame(df, numCols, hashSeed, factorMode));
    return __result;
END_RCPP
}
