// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// hashDataFrame
DataFrame hashDataFrame(DataFrame df, int numCols, int hashSeed);
RcppExport SEXP amsteRdam_hashDataFrame(SEXP dfSEXP, SEXP numColsSEXP, SEXP hashSeedSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< int >::type numCols(numColsSEXP);
    Rcpp::traits::input_parameter< int >::type hashSeed(hashSeedSEXP);
    __result = Rcpp::wrap(hashDataFrame(df, numCols, hashSeed));
    return __result;
END_RCPP
}
