# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Hashes the data frame, so the output contains much smaller number of columns.
#'
#' Calculates the reduced representation of the given data frame based on the
#' hashing trick.
#'
#' @param df Data frame to be hashed.
#' @param numCols Integer, number of columns for the output data frame.
#' @param hashSeed Integer, seed for the employed hash function (MurmurHash3).
#'
#' @return Data frame having \code{numCols} columns, containing combination of
#' columns from \code{df} according to hashing function.
#' @export
hashDataFrame <- function(df, numCols, hashSeed) {
    .Call('amsteRdam_hashDataFrame', PACKAGE = 'amsteRdam', df, numCols, hashSeed)
}

#' Provides explanation, how given data frame will be hashed.
#'
#' Function creates a data structure describing the hashing process.
#'
#' @param df Data frame to be hashed.
#' @param numCols Integer, number of columns for the output data frame.
#' @param hashSeed Integer, seed for the employed hash function (MurmurHash3).
#'
#' @return List of integer vectors. Each entry in list corresponds to one column
#' in the output of hashing. Entries in integer vectors give signs and names of integer
#' vector entries provide names of columns in original data frame.
#'
#' @export
explainHashDataFrame <- function(df, numCols, hashSeed) {
    .Call('amsteRdam_explainHashDataFrame', PACKAGE = 'amsteRdam', df, numCols, hashSeed)
}

