# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Hashes the data frame \code{df}, so the output contains \code{numCols}
#'
#' @param df data frame to be hashed
#' @param numCols integer, number of columns for the output data frame
#' @param hashSeed integer, seed for the employed hash function (MurmurHash3)
#' @export
hashDataFrame <- function(df, numCols, hashSeed) {
    .Call('amsteRdam_hashDataFrame', PACKAGE = 'amsteRdam', df, numCols, hashSeed)
}

